[package]
name = "pastral-ipc-schema"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
pastral-domain = { path = "../domain" }
pastral-ipc-core = { path = "../ipc-core" }
protobuf.workspace = true
sha2.workspace = true
uuid.workspace = true

[build-dependencies]
protobuf-codegen.workspace = true
