[package]
name = "pastral-manager-ipc-bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pastral-domain = { path = "../domain" }
pastral-ipc-core = { path = "../ipc-core" }
pastral-ipc-schema = { path = "../ipc-schema" }
pastral-ipc-win = { path = "../ipc-win" }

[dev-dependencies]
pastral-agent = { path = "../../apps/agent", features = ["ipc-health"] }
pastral-ipc-auth = { path = "../ipc-auth" }
pastral-storage = { path = "../storage" }
